### ISSUE TITLE
Karaf/OSGi support planned?

### ISSUE THREAD

**Issue by JulianSchuette** [ctron/de.dentrassi.camel.milo#2]
Great work! Thank you for this component. I was wondering if there are any plans to add OSGi headers to MANIFEST.MF or even greater, wrap it as a Karaf feature?

**Comment by ctron** [comment]
It should already be. If not it will become next week since I will need that myself ;-)

**Comment by ctron** [comment]
I just did check and found that the OSGi metadata already is being generated.

**Comment by ctron** [comment]
I did push a new SNAPSHOT version to OSSRH

**Comment by JulianSchuette** [comment]
Works now with the milo fixes from eclipse/milo#61 and eclipse/milo#59. Thank you!

**Comment by ctron** [comment]
Thank you for testing and reporting!
