### ISSUE TITLE
Tight dependency on camel-core version

### ISSUE THREAD

**Issue by JulianSchuette** [ctron/de.dentrassi.camel.milo#7]
The feature currently depends on the camel-core bundle in a specific version. Currently (8981dcf), it is set to 2.17.3:

`<bundle dependency="true">mvn:org.apache.camel/camel-core/${apache-camel-version}</bundle>`

If I'm not mistaken, this makes the feature incompatible even with other minor or patch versions, e.g. it cannot be used with recent camel 2.18. Is it planned to release this feature along with each matching camel release or would it be an alternative to replace the bundle dependency with a feature dependency with version ranges (which seems to work with my camel-core 2.18.0):

`<feature prerequisite="false" dependency="true" version="[2.17.0,3)">camel-core</feature>`

Thank you for the great contribution anyway!

**Comment by ctron** [comment]
To be honest, I am not that familiar how Karaf packaging works best. If you know more, just open a PR ;-)

**Comment by JulianSchuette** [comment]
Here is the PR, but I guess you won't like it :-) My fix for integrating this plugin into Camel 2.18.0 was to bump its dependency and its version to 2.18.0, which seems to be common practice for camel plugins (see here for example https://github.com/apache/camel/blob/master/components/camel-ahc/pom.xml), but of course it totally breaks your original versioning scheme.
I'm fine with rejecting this PR, it's just the solution that works for me right now.

**Comment by ctron** [comment]
I published a new version to Maven Central a few minutes ago (version 0.1.1). This should fix this issue.

It should also fix this issue. Maybe you can give it another try and let me know! Thanks!

**Comment by JulianSchuette** [comment]
It solves the problem and allows a suitable camel-core version range. Thank you!

**Comment by ctron** [comment]
Thanks for the feedback!
